### PR TITLE
Fixes events only getting the first param

### LINKED ISSUE #15: Only first event parameter is given
## Symptoms

The `EventInterface` instance given to an attached event handler does not contain all the original arguments as parameters, only the first one at index `0` (retrievable via `$event->getParam(0)`).

## Steps to Reproduce

1. Attach a handler using the event manager to a WordPress hook that provides more than 1 argument, such as [`save_post`](https://developer.wordpress.org/reference/hooks/save_post/).
2. Inspect the event params via `$event->getParams()`.
3. Observe symptom.

## Possible Cause

In more than one place in the code, the `add_action` and `add_filter` abstraction wrappers are being given `1` for the `num_args` parameter. This was likely done since all attached handlers are wrapped, and in truth they only receive a single event.

However, in truth that number controls how many arguments WordPress passes to the handler. Internally, it uses `array_slice($arguments, 0, $num_args)`. WordPress developers say that this argument exists to allow hooking in PHP native functions, which unlike developer-defined functions cannot receive more arguments than they have declared parameters.

## Recommended Solution

Directly attaching functions that are not compatible as handlers should not be supported IMO. For example: attaching the native `trim()` function as a handler to [`the_title`](https://codex.wordpress.org/Plugin_API/Filter_Reference/the_title) filter (which accepts 2 parameters).

Therefore, it is my recommendation that the `num_args` parameter is set to `PHP_INT_MAX`, which effectively is equivalent to forcing WordPress to always provide _all_ of the triggered hook's arguments as parameters.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #15 

----

Also adds a functionality test for `WpEventManager`, which was apparently missing.

### CODE REVIEW

File: src/WordPress/WpEventManager.php [hunk 1]
```diff
@@ -238,6 +258,39 @@ public function __construct($enablePropagation = false)
...
     }
 
+    /**
+     * Retrieves the argument count value to pass to the native WordPress action and filter hooking functions.
+     *
+     * @since [*next-version*]
+     *
+     * @return int
+     */
+    protected function _getNumArgs()
```
Comment (XedinUnknown) [inline src/WordPress/WpEventManager.php]: Is something preventing the extraction of this into a trait?

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

File: src/WordPress/WpEventManager.php (hunk 1 above)
Comment (mecha) [reply src/WordPress/WpEventManager.php]: Weird question to ask :P Answer: no

But if you meant to ask me to extract it into a trait, I'd probably answer with: `10-4`

---

_Already on it_

File: src/WordPress/NumArgsAwareTrait.php [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+    /**
+     * Retrieves the argument count value to pass to the native WordPress action and filter hooking functions.
+     *
+     * @since [*next-version*]
+     *
+     * @return int The number of arguments.
+     */
+    protected function _getNumArgs()
+    {
+        return $this->numArgs;
```
Comment (XedinUnknown) [inline src/WordPress/NumArgsAwareTrait.php]: The property may have the value of `null`, because it can be un-initialized. Because this method promises an integer, I think it could be improved by casting the number to `(int)`.

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

**Review by XedinUnknown — APPROVED** [review]
